<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfCAzDX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfCAzDX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQfCAzDX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQfCAzDX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQfCAzDX\App_KernelDevDebugContainer([
    'container.build_hash' => 'QfCAzDX',
    'container.build_id' => '6856457a',
    'container.build_time' => 1600808355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfCAzDX');
