<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'show_all_holidays' => [[], ['_controller' => 'App\\Controller\\HolidayController::show'], [], [['text', '/api/hr']], [], []],
    'show_holiday' => [['eid'], ['eid' => -1, '_controller' => 'App\\Controller\\HolidayController::show'], [], [['variable', '/', '[^/]++', 'eid', true], ['text', '/api/employee']], [], []],
    'add_holiday' => [['eid'], ['_controller' => 'App\\Controller\\HolidayController::add'], [], [['text', '/holiday'], ['variable', '/', '[^/]++', 'eid', true], ['text', '/api/employee']], [], []],
    'delete_holiday' => [['eid', 'id'], ['_controller' => 'App\\Controller\\HolidayController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/holiday'], ['variable', '/', '[^/]++', 'eid', true], ['text', '/api/employee']], [], []],
    'validate_holiday' => [['eid', 'id'], ['_controller' => 'App\\Controller\\HolidayController::validate'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/holiday'], ['variable', '/', '[^/]++', 'eid', true], ['text', '/api/hr']], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/api/home']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/api/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/api/logout']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/api/user']], [], []],
];
